### PR TITLE
task/catch service object errors properly

### LINKED ISSUE #381: Catch service object errors properly
In transactions, specify type of error 
    e.g. create a custom ServiceException and/or look for RecordInvalid exceptions

Track individual call errors and add it to the OpenStruct

Look at the error that is returned by [action]! methods

### PR DESCRIPTION
**Pull request by jseraf**
Service objects were not properly accounting for expected errors leaving the potential to hide truly broken code. Updates account for the most likely scenario -- i.e. RecordInvalid errors.

Closes #381

### CODE REVIEW

File: app/services/grant_services/duplicate_dependencies.rb [hunk 1]
```diff
@@ -19,10 +19,12 @@ def self.call(original_grant:, new_grant:)
 
         end
         OpenStruct.new(success?: true)
-      rescue
-        errors = new_grant.errors.any? ? new_grant.errors.full_messages : 'An error occurred while duplicating this grant. Please try again.'
+      rescue ActiveRecord::RecordInvalid => invalid
         OpenStruct.new(success?: false,
-                       messages: errors)
+                       messages: invalid.record.errors.full_messages)
+      rescue ServiceError(invalid: invalid)
```
Comment (fanglinnw) [inline app/services/grant_services/duplicate_dependencies.rb:25]: the rescue syntax seems wrong here

File: app/errors/service_error.rb [hunk 2]
```diff
@@ -0,0 +1 @@
+class ServiceError < Exception; end
```
Comment (fanglinnw) [inline app/errors/service_error.rb:1]: custom exception should inherit from StandardError

Comment (fanglinnw) [reply app/errors/service_error.rb:1]: also, if you want to pass params to the initializer, it needs to be defined like this:
```
class MyError < StandardError
  attr_reader :thing
  def initialize(msg="My default message", thing="apple")
    @thing = thing
    super(msg)
  end
end

begin
  raise MyError.new("my message", "my thing")
rescue => e
  puts e.thing # "my thing"
end
```

https://www.honeybadger.io/blog/ruby-custom-exceptions/

File: app/services/grant_submission_form_services/new.rb [hunk 3]
```diff
@@ -29,6 +29,8 @@ def self.call(grant:, user:)
                                         is_mandatory: true,
                                         response_type: 'file_upload')
         end
+      rescue ActiveRecord::RecordInvalid => invalid
+        raise ServiceError(err: invalid)
```
Comment (fanglinnw) [inline app/services/grant_submission_form_services/new.rb:33]: this should be changed to be consistent with other usage:
            raise ServiceError.new(invalid: invalid)

File: spec/services/grant_services/new_spec.rb [hunk 4]
```diff
@@ -45,68 +45,14 @@
 
     context 'failures' do
       it 'returns a struct with .success? false' do
-        allow(GrantPermission).to receive(:create!).and_raise(StandardError)
+        new_grant.update(name: '')
         result = GrantServices::New.call(grant: new_grant, user: grant_creator)
         expect(result.success?).to be false
```
Comment (fanglinnw) [inline spec/services/grant_services/new_spec.rb:50]: should add a `expect` for the error message in the result

File: app/services/grant_services/new.rb [hunk 5]
```diff
@@ -17,9 +17,9 @@ def self.call(grant:, user:)
     rescue ActiveRecord::RecordInvalid => invalid
       OpenStruct.new(success?: false,
                      messages: invalid.record.errors.full_messages)
-    rescue ServiceError => err # throws an active record error
+    rescue ServiceError => invalid
```
Comment (fanglinnw) [inline app/services/grant_services/new.rb:20]: ServiceError needs to be changed to the new class name

Comment (jseraf) [reply app/services/grant_services/new.rb]: Thanks. Updated in 1282f7b below
